# Taken from https://realpython.com/python-continuous-integration/#connect-to-circleci
# And from https://circleci.com/docs/2.0/language-python/
# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/terminal_playing_cards

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install codecov
            pipenv install --dev
      # Step 3: cache dependencies
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # Step 4: run linter and tests
      - run:
          name: run tests
          command: |
            mkdir -p test-results/pytest
            pipenv run pytest -v --junit-xml=test-results/pytest/results.xml --cov
            pipenv run coverage html
            pipenv run pylint terminal_playing_cards --exit-zero
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
      # Step 5: post results to codecov
      - run:
          name: post to codecov
          command: codecov
